# The ogre looks big and slow. Movement will help you avoid his deadly attacks.
hero.moveRight(2)
hero.moveUp(1)
hero.attack("Grumus")
hero.moveDown(1)
hero.moveLeft(2)
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.attack("Grumus")
hero.moveRight(1)
